// Generated by tools/convert_limbo_structures.py from the original Java templates.
// Signs, inventories, writable books, item damage, and records are restored after placement.
export const LIMBO_STRUCTURE_METADATA = Object.freeze({
  "limbo_caveoutpost": {
    "containers": [
      {
        "chestType": "right",
        "items": [
          {
            "amount": 64,
            "slot": 0,
            "typeId": "minecraft:cobblestone"
          },
          {
            "amount": 64,
            "slot": 1,
            "typeId": "minecraft:cobblestone"
          },
          {
            "amount": 64,
            "slot": 2,
            "typeId": "minecraft:cobblestone"
          },
          {
            "amount": 64,
            "slot": 3,
            "typeId": "minecraft:cobblestone"
          },
          {
            "amount": 64,
            "slot": 4,
            "typeId": "minecraft:cobblestone"
          },
          {
            "amount": 64,
            "slot": 5,
            "typeId": "minecraft:cobblestone"
          },
          {
            "amount": 64,
            "slot": 6,
            "typeId": "minecraft:cobblestone"
          },
          {
            "amount": 64,
            "slot": 7,
            "typeId": "minecraft:cobblestone"
          },
          {
            "amount": 64,
            "slot": 8,
            "typeId": "minecraft:cobblestone"
          },
          {
            "amount": 64,
            "slot": 9,
            "typeId": "minecraft:gravel"
          },
          {
            "amount": 9,
            "slot": 10,
            "typeId": "minecraft:dripstone_block"
          },
          {
            "amount": 64,
            "slot": 12,
            "typeId": "minecraft:cobblestone"
          },
          {
            "amount": 64,
            "slot": 13,
            "typeId": "minecraft:cobblestone"
          },
          {
            "amount": 23,
            "slot": 14,
            "typeId": "minecraft:tuff"
          },
          {
            "amount": 64,
            "slot": 15,
            "typeId": "minecraft:cobblestone"
          },
          {
            "amount": 64,
            "slot": 16,
            "typeId": "minecraft:cobblestone"
          },
          {
            "amount": 3,
            "slot": 17,
            "typeId": "minecraft:granite"
          },
          {
            "amount": 64,
            "slot": 18,
            "typeId": "minecraft:cobblestone"
          },
          {
            "amount": 64,
            "slot": 19,
            "typeId": "minecraft:cobblestone"
          },
          {
            "amount": 64,
            "slot": 20,
            "typeId": "minecraft:cobblestone"
          },
          {
            "amount": 30,
            "slot": 21,
            "typeId": "minecraft:gravel"
          },
          {
            "amount": 9,
            "slot": 22,
            "typeId": "minecraft:cobblestone"
          },
          {
            "amount": 4,
            "slot": 23,
            "typeId": "minecraft:flint"
          }
        ],
        "position": [
          20,
          20,
          28
        ]
      }
    ],
    "records": [
      {
        "position": [
          21,
          20,
          20
        ],
        "typeId": "minecraft:music_disc_cat"
      },
      {
        "position": [
          31,
          20,
          22
        ],
        "typeId": "minecraft:music_disc_cat"
      }
    ],
    "signs": [
      {
        "position": [
          31,
          17,
          20
        ],
        "text": "Deeper into the\npeace inside\nthat weak\nmind of yours."
      },
      {
        "position": [
          31,
          17,
          21
        ],
        "text": "Fall deeper.\nFall deeper.\nFall deeper.\nFall deeper."
      },
      {
        "position": [
          28,
          21,
          19
        ],
        "text": "LET ME OUT\nI CAN'T\nPLEASE\nLET ME GO"
      },
      {
        "position": [
          18,
          22,
          21
        ],
        "text": "'s\nunderground\nhome\n"
      },
      {
        "position": [
          24,
          29,
          35
        ],
        "text": "Stay awake Stay\nawake Stay awake\nStay awake Stay\nawake Stay awake"
      }
    ],
    "sourceBlockEntities": {
      "minecraft:bed": 10,
      "minecraft:chest": 14,
      "minecraft:jukebox": 5,
      "minecraft:sign": 25
    }
  },
  "limbo_distastefulquandary": {
    "containers": [
      {
        "chestType": "single",
        "items": [
          {
            "amount": 1,
            "slot": 4,
            "typeId": "minecraft:lime_terracotta"
          },
          {
            "amount": 1,
            "slot": 12,
            "typeId": "minecraft:lime_terracotta"
          },
          {
            "amount": 1,
            "bookPages": [
              "§l§nTHINGS TO DO:\n\n§0- Construct farm.\n- Mining for diamonds, coal and iron.\n- Make memorial for §4§k[REDACTED]§0, §9§k[REDACTED]§0 and §5§k[REDACTED] \n§0- Expand base.",
              "",
              "",
              "",
              "I do miss them, really.\n\nWhenever I pick up this game, all I can think about is them and what happened all those years ago.\n\nAll the questions that remained unanswered. \n\nI hope they are okay now.",
              "I don't know.\n\nMaybe it's wishful thinking. I understand that §4§k[REDACTED] §0never really had the best homelife and that §5§k[REDACTED]§0 was pretty much the only reason she'd wake up in the morning.\n\nI'm probably looking too deeply into it.",
              "I sometimes wish we never played on that server because maybe they would still be talking to me now.\n\nWas I too harsh?\n\nI mean, I remember being real passionate about our clan, but. I wasn't... cruel.\n\nRight?",
              "This is stupid."
            ],
            "nameTag": "TO DO",
            "slot": 13,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "slot": 14,
            "typeId": "minecraft:lime_terracotta"
          },
          {
            "amount": 1,
            "slot": 22,
            "typeId": "minecraft:lime_terracotta"
          }
        ],
        "position": [
          12,
          1,
          6
        ]
      },
      {
        "chestType": "right",
        "items": [
          {
            "amount": 52,
            "slot": 0,
            "typeId": "minecraft:iron_ingot"
          },
          {
            "amount": 5,
            "slot": 1,
            "typeId": "minecraft:diamond"
          },
          {
            "amount": 1,
            "damage": 44,
            "slot": 18,
            "typeId": "minecraft:diamond_pickaxe"
          },
          {
            "amount": 1,
            "damage": 167,
            "slot": 19,
            "typeId": "minecraft:diamond_axe"
          }
        ],
        "position": [
          4,
          2,
          4
        ]
      },
      {
        "chestType": "left",
        "items": [
          {
            "amount": 1,
            "damage": 46,
            "slot": 0,
            "typeId": "minecraft:iron_sword"
          }
        ],
        "position": [
          5,
          2,
          4
        ]
      },
      {
        "chestType": "single",
        "items": [
          {
            "amount": 3,
            "slot": 0,
            "typeId": "thebrokenscript:name_missing"
          },
          {
            "amount": 6,
            "slot": 1,
            "typeId": "minecraft:coal"
          }
        ],
        "position": [
          11,
          2,
          8
        ]
      },
      {
        "chestType": "right",
        "items": [
          {
            "amount": 14,
            "slot": 0,
            "typeId": "minecraft:netherrack"
          },
          {
            "amount": 5,
            "slot": 1,
            "typeId": "minecraft:exposed_copper_grate"
          },
          {
            "amount": 64,
            "slot": 2,
            "typeId": "minecraft:birch_log"
          },
          {
            "amount": 1,
            "slot": 4,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 9,
            "typeId": "minecraft:dark_oak_planks"
          },
          {
            "amount": 64,
            "slot": 10,
            "typeId": "minecraft:oak_planks"
          },
          {
            "amount": 64,
            "slot": 11,
            "typeId": "minecraft:mangrove_planks"
          },
          {
            "amount": 1,
            "slot": 13,
            "typeId": "minecraft:allium"
          },
          {
            "amount": 64,
            "slot": 18,
            "typeId": "minecraft:cherry_log"
          },
          {
            "amount": 64,
            "slot": 19,
            "typeId": "minecraft:acacia_planks"
          },
          {
            "amount": 8,
            "slot": 20,
            "typeId": "minecraft:rose_bush"
          },
          {
            "amount": 9,
            "slot": 21,
            "typeId": "minecraft:silver_glazed_terracotta"
          },
          {
            "amount": 10,
            "slot": 22,
            "typeId": "minecraft:oxidized_copper"
          },
          {
            "amount": 15,
            "slot": 23,
            "typeId": "minecraft:stripped_crimson_hyphae"
          },
          {
            "amount": 1,
            "slot": 25,
            "typeId": "minecraft:cornflower"
          }
        ],
        "position": [
          4,
          3,
          4
        ]
      },
      {
        "chestType": "left",
        "items": [
          {
            "amount": 64,
            "slot": 9,
            "typeId": "minecraft:black_wool"
          },
          {
            "amount": 64,
            "slot": 10,
            "typeId": "minecraft:black_wool"
          },
          {
            "amount": 64,
            "slot": 11,
            "typeId": "minecraft:black_wool"
          },
          {
            "amount": 64,
            "slot": 12,
            "typeId": "minecraft:black_wool"
          },
          {
            "amount": 64,
            "slot": 13,
            "typeId": "minecraft:black_wool"
          },
          {
            "amount": 64,
            "slot": 14,
            "typeId": "minecraft:black_wool"
          },
          {
            "amount": 64,
            "slot": 15,
            "typeId": "minecraft:black_wool"
          },
          {
            "amount": 64,
            "slot": 16,
            "typeId": "minecraft:black_wool"
          },
          {
            "amount": 64,
            "slot": 17,
            "typeId": "minecraft:black_wool"
          },
          {
            "amount": 8,
            "slot": 18,
            "typeId": "minecraft:light_weighted_pressure_plate"
          },
          {
            "amount": 5,
            "slot": 19,
            "typeId": "minecraft:iron_door"
          },
          {
            "amount": 5,
            "slot": 20,
            "typeId": "minecraft:spruce_fence"
          },
          {
            "amount": 7,
            "slot": 21,
            "typeId": "minecraft:tuff_slab"
          },
          {
            "amount": 3,
            "slot": 22,
            "typeId": "minecraft:exposed_cut_copper_slab"
          },
          {
            "amount": 3,
            "slot": 23,
            "typeId": "minecraft:diorite"
          }
        ],
        "position": [
          5,
          3,
          4
        ]
      },
      {
        "chestType": "single",
        "items": [
          {
            "amount": 64,
            "slot": 0,
            "typeId": "minecraft:chicken"
          },
          {
            "amount": 64,
            "slot": 1,
            "typeId": "minecraft:chicken"
          },
          {
            "amount": 37,
            "slot": 2,
            "typeId": "minecraft:chicken"
          },
          {
            "amount": 32,
            "slot": 9,
            "typeId": "minecraft:cookie"
          },
          {
            "amount": 5,
            "slot": 18,
            "typeId": "minecraft:salmon"
          }
        ],
        "position": [
          5,
          3,
          6
        ]
      },
      {
        "chestType": "single",
        "items": [
          {
            "amount": 17,
            "slot": 0,
            "typeId": "thebrokenscript:name_missing"
          },
          {
            "amount": 1,
            "slot": 1,
            "typeId": "minecraft:coal"
          }
        ],
        "position": [
          11,
          3,
          8
        ]
      }
    ],
    "records": [],
    "signs": [
      {
        "position": [
          2,
          1,
          8
        ],
        "text": "The day I\ntrust you is\nthe day I wind\nup dead."
      },
      {
        "position": [
          11,
          1,
          0
        ],
        "text": "Do it, then.\nI know you\nwant to.\nDo. It."
      },
      {
        "position": [
          7,
          2,
          3
        ],
        "text": "When did I make\nthis hallway so...\nbizarre.\n"
      },
      {
        "position": [
          13,
          2,
          3
        ],
        "text": "Like, seriously. :)\nYou should be\na writer of\nsome sorts. "
      },
      {
        "position": [
          7,
          3,
          3
        ],
        "text": "I never\ndid this.\nI don't. Think\nI did, anyway."
      },
      {
        "position": [
          12,
          3,
          4
        ],
        "text": "I mean, you\nhave me hooked.\nHaha.\n"
      },
      {
        "position": [
          13,
          3,
          3
        ],
        "text": "Close a door,\nanother one\nopens. Haha. So\npoetic."
      },
      {
        "position": [
          4,
          4,
          8
        ],
        "text": "===============\nSTORAGE\nSTORAGE\n==============="
      },
      {
        "position": [
          13,
          4,
          14
        ],
        "text": "Such a shame,\nI rather liked\nthis one.\n"
      },
      {
        "position": [
          14,
          6,
          10
        ],
        "text": "Fuck you.\n\n\n"
      },
      {
        "position": [
          4,
          9,
          5
        ],
        "text": "It's because of\nthings like you\nthat they never\ncame back."
      },
      {
        "position": [
          4,
          9,
          6
        ],
        "text": "upon my\nscreen?\n\n"
      },
      {
        "position": [
          4,
          9,
          7
        ],
        "text": "a being of such\ndivine absurdity\nthat has taken\nunwanted refuge"
      },
      {
        "position": [
          5,
          9,
          3
        ],
        "text": "It all makes\nsense now.\nI'm awake.\nI've awoken."
      },
      {
        "position": [
          5,
          9,
          8
        ],
        "text": "So, why am I\nyet again at my\ndecrepit desk,\ngazing down"
      },
      {
        "position": [
          6,
          9,
          9
        ],
        "text": "I said I'd never\nfall for this\nblatant\ncreepypasta shit."
      }
    ],
    "sourceBlockEntities": {
      "minecraft:chest": 9,
      "minecraft:furnace": 10,
      "minecraft:jukebox": 1,
      "minecraft:sign": 16
    }
  },
  "limbo_happyfarm": {
    "containers": [],
    "records": [],
    "signs": [
      {
        "position": [
          4,
          1,
          12
        ],
        "text": "thank you\nfor blessing me\nwith something\nreal"
      },
      {
        "position": [
          4,
          2,
          11
        ],
        "text": "i love this home\n\n\n"
      },
      {
        "position": [
          7,
          2,
          14
        ],
        "text": "barry's\npen\n\n"
      },
      {
        "position": [
          9,
          2,
          16
        ],
        "text": "Why aren't\nthey real?\nWhy are they\nlooking at"
      },
      {
        "position": [
          13,
          2,
          15
        ],
        "text": "tree\n\n\n"
      },
      {
        "position": [
          14,
          2,
          12
        ],
        "text": "cloud\n\n\n"
      },
      {
        "position": [
          4,
          3,
          12
        ],
        "text": "my home is so\nnice\n\n"
      },
      {
        "position": [
          9,
          3,
          16
        ],
        "text": "I don't like\nhow they are\nlooking at\nm"
      },
      {
        "position": [
          4,
          4,
          11
        ],
        "text": "my farm\nmy sheep\nmy beautiful\nsheep"
      },
      {
        "position": [
          9,
          4,
          16
        ],
        "text": "this isnt\nright\nthey arent\nreal"
      },
      {
        "position": [
          12,
          4,
          14
        ],
        "text": "leaves\n\n\n"
      },
      {
        "position": [
          4,
          5,
          12
        ],
        "text": "so kind\nso benevolent\n\n"
      },
      {
        "position": [
          9,
          5,
          16
        ],
        "text": "why arent\nthey real\nit promised me\ni could keep"
      },
      {
        "position": [
          14,
          5,
          14
        ],
        "text": "sky\n\n\n"
      }
    ],
    "sourceBlockEntities": {
      "minecraft:sign": 14
    }
  },
  "limbo_house": {
    "containers": [],
    "records": [],
    "signs": [
      {
        "position": [
          5,
          0,
          5
        ],
        "text": "0 0 0\n0 0 0\n0 0 0\n0 0 0"
      }
    ],
    "sourceBlockEntities": {
      "minecraft:sign": 1
    }
  },
  "limbo_sanctuary": {
    "containers": [
      {
        "chestType": "right",
        "items": [
          {
            "amount": 64,
            "slot": 0,
            "typeId": "minecraft:birch_planks"
          },
          {
            "amount": 64,
            "slot": 1,
            "typeId": "minecraft:birch_planks"
          },
          {
            "amount": 64,
            "slot": 2,
            "typeId": "minecraft:birch_planks"
          },
          {
            "amount": 35,
            "slot": 3,
            "typeId": "minecraft:birch_planks"
          },
          {
            "amount": 64,
            "slot": 9,
            "typeId": "minecraft:oak_planks"
          },
          {
            "amount": 4,
            "slot": 10,
            "typeId": "minecraft:oak_planks"
          },
          {
            "amount": 4,
            "slot": 18,
            "typeId": "minecraft:birch_stairs"
          }
        ],
        "position": [
          12,
          2,
          4
        ]
      },
      {
        "chestType": "left",
        "items": [
          {
            "amount": 1,
            "slot": 0,
            "typeId": "minecraft:birch_slab"
          },
          {
            "amount": 10,
            "slot": 9,
            "typeId": "minecraft:birch_trapdoor"
          }
        ],
        "position": [
          13,
          2,
          4
        ]
      },
      {
        "chestType": "single",
        "items": [
          {
            "amount": 11,
            "slot": 1,
            "typeId": "minecraft:coal"
          }
        ],
        "position": [
          18,
          2,
          4
        ]
      },
      {
        "chestType": "single",
        "items": [
          {
            "amount": 14,
            "slot": 1,
            "typeId": "minecraft:coal"
          }
        ],
        "position": [
          18,
          2,
          5
        ]
      },
      {
        "chestType": "single",
        "items": [
          {
            "amount": 37,
            "slot": 1,
            "typeId": "minecraft:coal"
          }
        ],
        "position": [
          18,
          2,
          6
        ]
      },
      {
        "chestType": "right",
        "items": [
          {
            "amount": 64,
            "slot": 0,
            "typeId": "minecraft:cobblestone"
          },
          {
            "amount": 32,
            "slot": 1,
            "typeId": "minecraft:dirt"
          }
        ],
        "position": [
          12,
          3,
          4
        ]
      },
      {
        "chestType": "single",
        "items": [
          {
            "amount": 3,
            "slot": 1,
            "typeId": "minecraft:coal"
          }
        ],
        "position": [
          18,
          3,
          4
        ]
      },
      {
        "chestType": "single",
        "items": [
          {
            "amount": 10,
            "slot": 1,
            "typeId": "minecraft:coal"
          }
        ],
        "position": [
          18,
          3,
          5
        ]
      },
      {
        "chestType": "single",
        "items": [
          {
            "amount": 22,
            "slot": 1,
            "typeId": "minecraft:coal"
          }
        ],
        "position": [
          18,
          3,
          6
        ]
      },
      {
        "chestType": "single",
        "items": [
          {
            "amount": 1,
            "slot": 2,
            "typeId": "minecraft:black_stained_glass_pane"
          },
          {
            "amount": 1,
            "slot": 3,
            "typeId": "minecraft:black_stained_glass_pane"
          },
          {
            "amount": 1,
            "slot": 4,
            "typeId": "minecraft:black_stained_glass_pane"
          },
          {
            "amount": 1,
            "slot": 5,
            "typeId": "minecraft:black_stained_glass_pane"
          },
          {
            "amount": 1,
            "slot": 6,
            "typeId": "minecraft:black_stained_glass_pane"
          },
          {
            "amount": 1,
            "slot": 10,
            "typeId": "minecraft:black_stained_glass_pane"
          },
          {
            "amount": 1,
            "slot": 11,
            "typeId": "minecraft:white_stained_glass_pane"
          },
          {
            "amount": 1,
            "slot": 12,
            "typeId": "minecraft:white_stained_glass_pane"
          },
          {
            "amount": 1,
            "slot": 13,
            "typeId": "minecraft:green_stained_glass_pane"
          },
          {
            "amount": 1,
            "slot": 14,
            "typeId": "minecraft:white_stained_glass_pane"
          },
          {
            "amount": 1,
            "slot": 15,
            "typeId": "minecraft:white_stained_glass_pane"
          },
          {
            "amount": 1,
            "slot": 16,
            "typeId": "minecraft:black_stained_glass_pane"
          },
          {
            "amount": 1,
            "slot": 20,
            "typeId": "minecraft:black_stained_glass_pane"
          },
          {
            "amount": 1,
            "slot": 21,
            "typeId": "minecraft:black_stained_glass_pane"
          },
          {
            "amount": 1,
            "slot": 22,
            "typeId": "minecraft:black_stained_glass_pane"
          },
          {
            "amount": 1,
            "slot": 23,
            "typeId": "minecraft:black_stained_glass_pane"
          },
          {
            "amount": 1,
            "slot": 24,
            "typeId": "minecraft:black_stained_glass_pane"
          }
        ],
        "position": [
          13,
          18,
          4
        ]
      },
      {
        "chestType": "single",
        "items": [
          {
            "amount": 1,
            "slot": 0,
            "typeId": "minecraft:white_carpet"
          },
          {
            "amount": 1,
            "slot": 1,
            "typeId": "minecraft:trapdoor"
          },
          {
            "amount": 1,
            "slot": 2,
            "typeId": "minecraft:red_nether_brick"
          },
          {
            "amount": 1,
            "slot": 3,
            "typeId": "minecraft:twisting_vines"
          },
          {
            "amount": 1,
            "slot": 4,
            "typeId": "minecraft:heavy_weighted_pressure_plate"
          },
          {
            "amount": 1,
            "slot": 5,
            "typeId": "minecraft:banner"
          },
          {
            "amount": 1,
            "slot": 6,
            "typeId": "minecraft:exposed_copper_grate"
          },
          {
            "amount": 1,
            "slot": 7,
            "typeId": "minecraft:spruce_button"
          },
          {
            "amount": 1,
            "slot": 8,
            "typeId": "minecraft:small_amethyst_bud"
          },
          {
            "amount": 1,
            "slot": 10,
            "typeId": "minecraft:waxed_oxidized_copper_trapdoor"
          },
          {
            "amount": 1,
            "slot": 11,
            "typeId": "minecraft:frame"
          },
          {
            "amount": 1,
            "slot": 12,
            "typeId": "minecraft:mojang_banner_pattern"
          },
          {
            "amount": 1,
            "slot": 13,
            "typeId": "minecraft:honeycomb_block"
          },
          {
            "amount": 1,
            "slot": 14,
            "typeId": "minecraft:bed"
          },
          {
            "amount": 1,
            "slot": 15,
            "typeId": "minecraft:painting"
          },
          {
            "amount": 1,
            "slot": 16,
            "typeId": "minecraft:tripwire_hook"
          },
          {
            "amount": 1,
            "slot": 21,
            "typeId": "minecraft:melon_seeds"
          },
          {
            "amount": 1,
            "slot": 23,
            "typeId": "minecraft:empty_map"
          }
        ],
        "position": [
          13,
          18,
          5
        ]
      },
      {
        "chestType": "single",
        "items": [
          {
            "amount": 1,
            "slot": 1,
            "typeId": "minecraft:coal"
          }
        ],
        "position": [
          18,
          18,
          7
        ]
      },
      {
        "chestType": "single",
        "items": [
          {
            "amount": 1,
            "slot": 0,
            "typeId": "minecraft:birch_planks"
          },
          {
            "amount": 1,
            "slot": 1,
            "typeId": "minecraft:birch_trapdoor"
          },
          {
            "amount": 1,
            "slot": 3,
            "typeId": "minecraft:oak_planks"
          },
          {
            "amount": 1,
            "slot": 5,
            "typeId": "minecraft:birch_stairs"
          },
          {
            "amount": 1,
            "slot": 6,
            "typeId": "minecraft:oak_planks"
          },
          {
            "amount": 1,
            "slot": 9,
            "typeId": "minecraft:birch_planks"
          },
          {
            "amount": 1,
            "slot": 10,
            "typeId": "minecraft:birch_trapdoor"
          },
          {
            "amount": 1,
            "slot": 12,
            "typeId": "minecraft:oak_planks"
          },
          {
            "amount": 1,
            "slot": 14,
            "typeId": "minecraft:birch_stairs"
          },
          {
            "amount": 1,
            "slot": 15,
            "typeId": "minecraft:oak_planks"
          },
          {
            "amount": 1,
            "slot": 18,
            "typeId": "minecraft:birch_planks"
          },
          {
            "amount": 1,
            "slot": 19,
            "typeId": "minecraft:birch_trapdoor"
          },
          {
            "amount": 1,
            "slot": 21,
            "typeId": "minecraft:oak_planks"
          },
          {
            "amount": 1,
            "slot": 23,
            "typeId": "minecraft:birch_stairs"
          },
          {
            "amount": 1,
            "slot": 24,
            "typeId": "minecraft:oak_planks"
          }
        ],
        "position": [
          12,
          19,
          4
        ]
      },
      {
        "chestType": "single",
        "items": [
          {
            "amount": 2,
            "slot": 0,
            "typeId": "minecraft:furnace"
          },
          {
            "amount": 2,
            "slot": 1,
            "typeId": "minecraft:smoker"
          },
          {
            "amount": 2,
            "slot": 2,
            "typeId": "minecraft:blast_furnace"
          },
          {
            "amount": 1,
            "slot": 8,
            "typeId": "minecraft:bed"
          },
          {
            "amount": 3,
            "slot": 18,
            "typeId": "minecraft:chest"
          },
          {
            "amount": 3,
            "slot": 19,
            "typeId": "minecraft:chest"
          },
          {
            "amount": 1,
            "slot": 26,
            "typeId": "minecraft:crafting_table"
          }
        ],
        "position": [
          14,
          19,
          4
        ]
      },
      {
        "chestType": "single",
        "items": [
          {
            "amount": 1,
            "slot": 0,
            "typeId": "minecraft:smoker"
          }
        ],
        "position": [
          17,
          19,
          5
        ]
      },
      {
        "chestType": "single",
        "items": [
          {
            "amount": 1,
            "nameTag": "This place is home.",
            "slot": 0,
            "typeId": "minecraft:paper"
          }
        ],
        "position": [
          19,
          19,
          4
        ]
      },
      {
        "chestType": "single",
        "items": [
          {
            "amount": 1,
            "slot": 0,
            "typeId": "minecraft:red_wool"
          },
          {
            "amount": 1,
            "slot": 1,
            "typeId": "minecraft:red_wool"
          },
          {
            "amount": 1,
            "slot": 2,
            "typeId": "minecraft:red_wool"
          },
          {
            "amount": 1,
            "slot": 3,
            "typeId": "minecraft:red_wool"
          },
          {
            "amount": 1,
            "slot": 4,
            "typeId": "minecraft:red_wool"
          },
          {
            "amount": 1,
            "slot": 5,
            "typeId": "minecraft:red_wool"
          },
          {
            "amount": 1,
            "slot": 6,
            "typeId": "minecraft:red_wool"
          },
          {
            "amount": 1,
            "slot": 7,
            "typeId": "minecraft:red_wool"
          },
          {
            "amount": 1,
            "slot": 8,
            "typeId": "minecraft:red_wool"
          },
          {
            "amount": 1,
            "slot": 9,
            "typeId": "minecraft:red_wool"
          },
          {
            "amount": 1,
            "slot": 10,
            "typeId": "minecraft:mutton"
          },
          {
            "amount": 1,
            "slot": 11,
            "typeId": "minecraft:mutton"
          },
          {
            "amount": 1,
            "slot": 12,
            "typeId": "minecraft:mutton"
          },
          {
            "amount": 1,
            "slot": 13,
            "typeId": "minecraft:mutton"
          },
          {
            "amount": 1,
            "slot": 14,
            "typeId": "minecraft:mutton"
          },
          {
            "amount": 1,
            "slot": 15,
            "typeId": "minecraft:mutton"
          },
          {
            "amount": 1,
            "slot": 16,
            "typeId": "minecraft:mutton"
          },
          {
            "amount": 1,
            "slot": 17,
            "typeId": "minecraft:red_wool"
          },
          {
            "amount": 1,
            "slot": 18,
            "typeId": "minecraft:red_wool"
          },
          {
            "amount": 1,
            "slot": 19,
            "typeId": "minecraft:red_wool"
          },
          {
            "amount": 1,
            "slot": 20,
            "typeId": "minecraft:red_wool"
          },
          {
            "amount": 1,
            "slot": 21,
            "typeId": "minecraft:red_wool"
          },
          {
            "amount": 1,
            "slot": 22,
            "typeId": "minecraft:red_wool"
          },
          {
            "amount": 1,
            "slot": 23,
            "typeId": "minecraft:red_wool"
          },
          {
            "amount": 1,
            "slot": 24,
            "typeId": "minecraft:red_wool"
          },
          {
            "amount": 1,
            "slot": 25,
            "typeId": "minecraft:red_wool"
          },
          {
            "amount": 1,
            "slot": 26,
            "typeId": "minecraft:red_wool"
          }
        ],
        "position": [
          13,
          20,
          4
        ]
      },
      {
        "chestType": "single",
        "items": [
          {
            "amount": 1,
            "slot": 0,
            "typeId": "minecraft:chest"
          },
          {
            "amount": 1,
            "slot": 1,
            "typeId": "minecraft:chest"
          },
          {
            "amount": 1,
            "slot": 2,
            "typeId": "minecraft:chest"
          },
          {
            "amount": 1,
            "slot": 3,
            "typeId": "minecraft:chest"
          },
          {
            "amount": 1,
            "slot": 4,
            "typeId": "minecraft:chest"
          },
          {
            "amount": 1,
            "slot": 5,
            "typeId": "minecraft:chest"
          },
          {
            "amount": 1,
            "slot": 6,
            "typeId": "minecraft:chest"
          },
          {
            "amount": 1,
            "slot": 7,
            "typeId": "minecraft:chest"
          },
          {
            "amount": 1,
            "slot": 8,
            "typeId": "minecraft:chest"
          },
          {
            "amount": 1,
            "slot": 9,
            "typeId": "minecraft:chest"
          },
          {
            "amount": 1,
            "slot": 10,
            "typeId": "minecraft:chest"
          },
          {
            "amount": 1,
            "slot": 11,
            "typeId": "minecraft:chest"
          },
          {
            "amount": 1,
            "slot": 12,
            "typeId": "minecraft:chest"
          },
          {
            "amount": 1,
            "slot": 13,
            "typeId": "minecraft:chest"
          },
          {
            "amount": 1,
            "slot": 14,
            "typeId": "minecraft:chest"
          },
          {
            "amount": 1,
            "slot": 15,
            "typeId": "minecraft:chest"
          },
          {
            "amount": 1,
            "slot": 16,
            "typeId": "minecraft:chest"
          },
          {
            "amount": 1,
            "slot": 17,
            "typeId": "minecraft:chest"
          },
          {
            "amount": 1,
            "slot": 18,
            "typeId": "minecraft:chest"
          },
          {
            "amount": 1,
            "slot": 19,
            "typeId": "minecraft:chest"
          },
          {
            "amount": 1,
            "slot": 20,
            "typeId": "minecraft:chest"
          },
          {
            "amount": 1,
            "slot": 21,
            "typeId": "minecraft:chest"
          },
          {
            "amount": 1,
            "slot": 22,
            "typeId": "minecraft:chest"
          },
          {
            "amount": 1,
            "slot": 23,
            "typeId": "minecraft:chest"
          },
          {
            "amount": 1,
            "slot": 24,
            "typeId": "minecraft:chest"
          },
          {
            "amount": 1,
            "slot": 25,
            "typeId": "minecraft:chest"
          },
          {
            "amount": 1,
            "slot": 26,
            "typeId": "minecraft:chest"
          }
        ],
        "position": [
          15,
          20,
          5
        ]
      }
    ],
    "records": [],
    "signs": [
      {
        "position": [
          18,
          14,
          7
        ],
        "text": "This place\nbrings you\nlove.\nlove."
      },
      {
        "position": [
          18,
          14,
          8
        ],
        "text": "This place\nbrings you\njoy.\njoy."
      },
      {
        "position": [
          18,
          15,
          7
        ],
        "text": "This place\nbrings you\nhappiness.\nhappiness."
      },
      {
        "position": [
          18,
          15,
          8
        ],
        "text": "This place\nbrings you\npeace.\npeace."
      },
      {
        "position": [
          18,
          16,
          7
        ],
        "text": "This place\nbrings you\nsafety.\nsafety."
      },
      {
        "position": [
          18,
          16,
          8
        ],
        "text": "This place\nbrings you\ncomfort.\ncomfort."
      },
      {
        "position": [
          12,
          22,
          4
        ],
        "text": "I know this isn't.\nI know this isn't.\nI know this isn't.\nI know this isn't."
      },
      {
        "position": [
          12,
          22,
          5
        ],
        "text": "I know this isn't.\nI know this isn't.\nI know this isn't.\nI know this isn't."
      },
      {
        "position": [
          13,
          22,
          6
        ],
        "text": "I know this isn't.\nI know this isn't.\nI know this isn't.\nI know this isn't."
      },
      {
        "position": [
          13,
          22,
          10
        ],
        "text": "I know this isn't.\nI know this isn't.\nI know this isn't.\nI know this isn't."
      },
      {
        "position": [
          13,
          22,
          11
        ],
        "text": "I know this isn't.\nI know this isn't.\nI know this isn't.\nI know this isn't."
      },
      {
        "position": [
          14,
          22,
          5
        ],
        "text": "I know this isn't.\nI know this isn't.\nI know this isn't.\nI know this isn't."
      },
      {
        "position": [
          17,
          22,
          5
        ],
        "text": "I know this isn't.\nI know this isn't.\nI know this isn't.\nI know this isn't."
      },
      {
        "position": [
          17,
          23,
          4
        ],
        "text": "I know this isn't.\nI know this isn't.\nI know this isn't.\nI know this isn't."
      },
      {
        "position": [
          18,
          23,
          7
        ],
        "text": "I know this isn't.\nI know this isn't.\nI know this isn't.\nI know this isn't."
      },
      {
        "position": [
          12,
          24,
          7
        ],
        "text": "I know this isn't.\nI know this isn't.\nI know this isn't.\nI know this isn't."
      },
      {
        "position": [
          17,
          24,
          4
        ],
        "text": "I know this isn't.\nI know this isn't.\nI know this isn't.\nI know this isn't."
      },
      {
        "position": [
          18,
          24,
          4
        ],
        "text": "I know this isn't.\nI know this isn't.\nI know this isn't.\nI know this isn't."
      },
      {
        "position": [
          12,
          25,
          10
        ],
        "text": "I know this isn't.\nI know this isn't.\nI know this isn't.\nI know this isn't."
      },
      {
        "position": [
          14,
          25,
          4
        ],
        "text": "I know this isn't.\nI know this isn't.\nI know this isn't.\nI know this isn't."
      },
      {
        "position": [
          16,
          26,
          5
        ],
        "text": "I know this isn't.\nI know this isn't.\nI know this isn't.\nI know this isn't."
      },
      {
        "position": [
          13,
          27,
          8
        ],
        "text": "I know this isn't.\nI know this isn't.\nI know this isn't.\nI know this isn't."
      },
      {
        "position": [
          14,
          27,
          10
        ],
        "text": "I know this isn't.\nI know this isn't.\nI know this isn't.\nI know this isn't."
      },
      {
        "position": [
          14,
          28,
          7
        ],
        "text": "I know this isn't.\nI know this isn't.\nI know this isn't.\nI know this isn't."
      },
      {
        "position": [
          16,
          28,
          7
        ],
        "text": "I know this isn't.\nI know this isn't.\nI know this isn't.\nI know this isn't."
      }
    ],
    "sourceBlockEntities": {
      "minecraft:bed": 10,
      "minecraft:blast_furnace": 5,
      "minecraft:chest": 12,
      "minecraft:furnace": 5,
      "minecraft:sign": 25,
      "minecraft:smoker": 5
    }
  },
  "limbo_somethingoldsomethingnew": {
    "containers": [
      {
        "chestType": "right",
        "items": [
          {
            "amount": 64,
            "slot": 0,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 1,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 2,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 3,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 4,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 5,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 6,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 7,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 8,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 9,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 10,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 11,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 12,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 13,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 14,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 15,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 16,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 17,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 18,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 19,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 20,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 21,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 22,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 23,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 24,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 25,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 26,
            "typeId": "minecraft:poppy"
          }
        ],
        "position": [
          3,
          6,
          17
        ]
      },
      {
        "chestType": "left",
        "items": [
          {
            "amount": 64,
            "slot": 0,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 1,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 2,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 3,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 4,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 5,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 6,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 7,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 8,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 9,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 10,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 11,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 12,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 13,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 14,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 15,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 16,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 17,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 18,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 19,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 20,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 21,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 22,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 23,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 24,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 25,
            "typeId": "minecraft:poppy"
          },
          {
            "amount": 64,
            "slot": 26,
            "typeId": "minecraft:poppy"
          }
        ],
        "position": [
          4,
          6,
          17
        ]
      }
    ],
    "records": [],
    "signs": [
      {
        "position": [
          7,
          1,
          15
        ],
        "text": "Why does it look\nlike this? No, no.\nIt's all wrong.\n"
      },
      {
        "position": [
          9,
          1,
          15
        ],
        "text": "Ohhhh.\n\n\n"
      },
      {
        "position": [
          2,
          2,
          15
        ],
        "text": "I don't get it.\n\n\n"
      },
      {
        "position": [
          8,
          2,
          15
        ],
        "text": "This isn't the\nright base.\n\n"
      },
      {
        "position": [
          9,
          2,
          15
        ],
        "text": "OOOOOk.\nYeah yeah\nyeah. Awesome.\n"
      },
      {
        "position": [
          12,
          2,
          9
        ],
        "text": "Oh, right.\nI see.\n\n"
      },
      {
        "position": [
          14,
          2,
          9
        ],
        "text": "No?\n\n\n"
      },
      {
        "position": [
          14,
          2,
          10
        ],
        "text": "What?\n\n\n"
      },
      {
        "position": [
          2,
          3,
          15
        ],
        "text": "why this house?\n\n\n"
      },
      {
        "position": [
          13,
          3,
          8
        ],
        "text": "I feel as if\nI've been here\nbefore.\n"
      },
      {
        "position": [
          14,
          3,
          10
        ],
        "text": "Oh, hey.\n\n\n"
      }
    ],
    "sourceBlockEntities": {
      "minecraft:chest": 17,
      "minecraft:enchanting_table": 1,
      "minecraft:furnace": 8,
      "minecraft:jukebox": 1,
      "minecraft:sign": 25
    }
  },
  "limbo_thewrongdirection": {
    "containers": [],
    "records": [],
    "signs": [
      {
        "position": [
          16,
          3,
          6
        ],
        "text": "it see?\nhurt me\n\n"
      },
      {
        "position": [
          15,
          4,
          3
        ],
        "text": "let me\nbe it my\nmy\n"
      },
      {
        "position": [
          17,
          5,
          5
        ],
        "text": "it said would\nmy\n\n"
      },
      {
        "position": [
          14,
          6,
          3
        ],
        "text": "why\nme so?\n\n"
      },
      {
        "position": [
          12,
          7,
          7
        ],
        "text": "would\n\noddities.\n"
      },
      {
        "position": [
          2,
          8,
          5
        ],
        "text": "so can't\ni\ndoes\n"
      },
      {
        "position": [
          6,
          8,
          3
        ],
        "text": "looking\nin the\nright\ndirection"
      },
      {
        "position": [
          6,
          8,
          6
        ],
        "text": "gnikool\nni eht\ngnorw\nnoitcerid"
      },
      {
        "position": [
          12,
          8,
          4
        ],
        "text": "embrace\n\nwhy\n"
      },
      {
        "position": [
          17,
          8,
          3
        ],
        "text": "free. enhance\nlife.\n\n"
      },
      {
        "position": [
          16,
          11,
          3
        ],
        "text": "my\nbe\n\n"
      }
    ],
    "sourceBlockEntities": {
      "minecraft:chest": 5,
      "minecraft:sign": 11
    }
  },
  "limbo_towerbaseright": {
    "containers": [],
    "records": [],
    "signs": [
      {
        "position": [
          40,
          1,
          17
        ],
        "text": "wow u look so\ncool omg how did\nu get that skin\n"
      },
      {
        "position": [
          41,
          1,
          18
        ],
        "text": "its a mod???\no ok!!! :D\n\n"
      },
      {
        "position": [
          44,
          1,
          23
        ],
        "text": "no im \nsrry i didn\nwant 2 upset u\n"
      },
      {
        "position": [
          45,
          1,
          24
        ],
        "text": "y not\n\n\n"
      },
      {
        "position": [
          46,
          1,
          24
        ],
        "text": "oh ok\ncan i leave cause\nmom said about \ndinner at 4"
      },
      {
        "position": [
          47,
          1,
          24
        ],
        "text": "idk what u\nmean\n\n"
      },
      {
        "position": [
          45,
          2,
          24
        ],
        "text": "oh ok\n\n\n"
      },
      {
        "position": [
          46,
          2,
          15
        ],
        "text": "farm\n\n\n"
      },
      {
        "position": [
          41,
          19,
          23
        ],
        "text": "yay :DDDD\n\n\n"
      },
      {
        "position": [
          42,
          19,
          22
        ],
        "text": "kichen\n\n\n"
      },
      {
        "position": [
          42,
          19,
          24
        ],
        "text": "do u like my\nkichen\n\n"
      },
      {
        "position": [
          45,
          20,
          17
        ],
        "text": "meting tabl\n\n\n"
      },
      {
        "position": [
          46,
          20,
          20
        ],
        "text": "u have no\none 2 talk 2 :(\nim srry\n"
      },
      {
        "position": [
          46,
          20,
          21
        ],
        "text": "its so emptie\nhere lol\n\n"
      },
      {
        "position": [
          47,
          20,
          19
        ],
        "text": "oh ok i \nget it i fink\n\n"
      },
      {
        "position": [
          46,
          21,
          20
        ],
        "text": "ya we can be\nfrends!\ntho i really do\nneed 2 go"
      },
      {
        "position": [
          52,
          29,
          10
        ],
        "text": "um... ok...\n\n\n"
      },
      {
        "position": [
          33,
          30,
          9
        ],
        "text": "idk y i cant\nget miself 2\nlog off i need 2\neat dinner :("
      },
      {
        "position": [
          33,
          30,
          12
        ],
        "text": "oh srry no i\nwont i swer :(((\njust hungrie lol\n"
      },
      {
        "position": [
          52,
          30,
          10
        ],
        "text": "ur acting wierd\npls stop :/\n\n"
      },
      {
        "position": [
          45,
          34,
          17
        ],
        "text": "its scary \ni dont like it\ni rlly dont like it\n"
      },
      {
        "position": [
          38,
          36,
          14
        ],
        "text": "stone\n\n\n"
      },
      {
        "position": [
          40,
          36,
          24
        ],
        "text": "wood\n\n\n"
      },
      {
        "position": [
          42,
          37,
          15
        ],
        "text": "daimonds\n\n\n"
      },
      {
        "position": [
          38,
          38,
          20
        ],
        "text": "soards\n\n\n"
      },
      {
        "position": [
          38,
          38,
          22
        ],
        "text": "shovals\n\n\n"
      },
      {
        "position": [
          43,
          38,
          14
        ],
        "text": "gardining\n\n\n"
      },
      {
        "position": [
          36,
          40,
          17
        ],
        "text": "storag\n\n\n"
      },
      {
        "position": [
          2,
          41,
          25
        ],
        "text": "PLDEWASE\n\n\n"
      },
      {
        "position": [
          3,
          41,
          27
        ],
        "text": "ddddddddddddddd\n\n\n"
      },
      {
        "position": [
          5,
          41,
          24
        ],
        "text": "noonhonb\n\n\n"
      },
      {
        "position": [
          11,
          41,
          20
        ],
        "text": "ims orry pl;s\nst opow\n\n"
      },
      {
        "position": [
          13,
          41,
          22
        ],
        "text": "pls stopo ims\nsrorry i wiobnt\ntry ti log ogg im\n"
      },
      {
        "position": [
          26,
          41,
          25
        ],
        "text": "my bed\n\n\n"
      },
      {
        "position": [
          22,
          42,
          16
        ],
        "text": "pool\n\n\n"
      },
      {
        "position": [
          50,
          46,
          25
        ],
        "text": "idk what to even\nsay\n\n"
      },
      {
        "position": [
          50,
          46,
          26
        ],
        "text": "i miss my \nfrends\n\n"
      },
      {
        "position": [
          29,
          51,
          18
        ],
        "text": "wait no\n\n\n"
      },
      {
        "position": [
          38,
          51,
          12
        ],
        "text": "??\n\n\n"
      },
      {
        "position": [
          43,
          51,
          27
        ],
        "text": "???????????????\n\n\n"
      },
      {
        "position": [
          36,
          53,
          16
        ],
        "text": "?????\n\n\n"
      }
    ],
    "sourceBlockEntities": {
      "minecraft:furnace": 33,
      "minecraft:sign": 43,
      "minecraft:trapped_chest": 139
    }
  },
  "limbo_treehouse": {
    "containers": [
      {
        "chestType": "single",
        "items": [
          {
            "amount": 1,
            "bookPages": [
              "It's cold.\n\nShe gave me a book to write in today.\n\nThat was nice of her.\n\nThis place is cold.\nBlistering cold.\nSo cold, I feel my skin freezing, but it never fully does.",
              "She checks on me.\nShe's nice.\n\nShe gave me somewhere to rest.\nTo sleep.\n\n\nI like sleeping.\nShe says it's good for me.",
              "\n\n\n\n\nIt's nice not being conscious. \n\n",
              "",
              "\n\n\n\n\nShe said she's looking for my friend.\n\n",
              "It's been lonely without them.\n\nEver since those two left us down there.\n\nShe tells me that they left me on purpose.\nThat she is helping.\n\nI trust her."
            ],
            "nameTag": "Seven",
            "slot": 13,
            "typeId": "minecraft:writable_book"
          }
        ],
        "position": [
          31,
          16,
          8
        ]
      },
      {
        "chestType": "left",
        "items": [
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 0,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 2,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 4,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 6,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 8,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 9,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 11,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 13,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 15,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 17,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 18,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 19,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 20,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 21,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 22,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 23,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 24,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 25,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 26,
            "typeId": "minecraft:writable_book"
          }
        ],
        "position": [
          1,
          20,
          20
        ]
      },
      {
        "chestType": "right",
        "items": [
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 0,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 1,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 2,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 3,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 4,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 5,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 6,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 7,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 8,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 9,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 11,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 13,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 15,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 17,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 18,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 20,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 22,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 24,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 26,
            "typeId": "minecraft:writable_book"
          }
        ],
        "position": [
          1,
          20,
          21
        ]
      },
      {
        "chestType": "single",
        "items": [
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 0,
            "typeId": "minecraft:writable_book"
          }
        ],
        "position": [
          7,
          20,
          20
        ]
      },
      {
        "chestType": "single",
        "items": [
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 4,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 9,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 10,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 11,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 12,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 13,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 14,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 15,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 16,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 17,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 22,
            "typeId": "minecraft:writable_book"
          }
        ],
        "position": [
          1,
          21,
          20
        ]
      },
      {
        "chestType": "single",
        "items": [
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 0,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 1,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 2,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 3,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 4,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 5,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 6,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 7,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 8,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 9,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 10,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 11,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 12,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 13,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 14,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 15,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 16,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 17,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 18,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 19,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 20,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 21,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 22,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 23,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 24,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 25,
            "typeId": "minecraft:writable_book"
          },
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 26,
            "typeId": "minecraft:writable_book"
          }
        ],
        "position": [
          1,
          21,
          21
        ]
      },
      {
        "chestType": "single",
        "items": [
          {
            "amount": 1,
            "bookPages": [
              "Stay."
            ],
            "nameTag": "Stay.",
            "slot": 0,
            "typeId": "minecraft:writable_book"
          }
        ],
        "position": [
          8,
          21,
          20
        ]
      }
    ],
    "records": [],
    "signs": [],
    "sourceBlockEntities": {
      "minecraft:banner": 7,
      "minecraft:bed": 8,
      "minecraft:chest": 5,
      "minecraft:furnace": 2
    }
  }
});
